# @Deprecated

# here we create a table listing all genome names for full bacterial genomes from NCBI as of 2008-06-05
# the directory names use underscores instead of spaces;
we fix that
# then we can check which of these names do not exist in the NCBI taxonomy names table

use ncbi_taxonomy;
drop table if exists tmp;
create table tmp (name_txt varchar(255));

insert into tmp values ('Acaryochloris marina MBIC11017');
insert into tmp values ('Acholeplasma laidlawii PG-8A');
insert into tmp values ('Acidiphilium cryptum JF-5');
insert into tmp values ('Acidobacteria bacterium Ellin345');
insert into tmp values ('Acidothermus cellulolyticus 11B');
insert into tmp values ('Acidovorax avenae subsp. citrulli AAC00-1');
insert into tmp values ('Acidovorax sp. JS42');
insert into tmp values ('Acinetobacter baumannii');
insert into tmp values ('Acinetobacter baumannii ATCC 17978');
insert into tmp values ('Acinetobacter baumannii AYE');
insert into tmp values ('Acinetobacter sp. ADP1');
insert into tmp values ('Actinobacillus pleuropneumoniae L20');
insert into tmp values ('Actinobacillus pleuropneumoniae serovar 3 str. JL03');
insert into tmp values ('Actinobacillus succinogenes 130Z');
insert into tmp values ('Aeromonas hydrophila subsp. hydrophila ATCC 7966');
insert into tmp values ('Aeromonas salmonicida subsp. salmonicida A449');
insert into tmp values ('Aeropyrum pernix K1');
insert into tmp values ('Agrobacterium tumefaciens str. C58');
insert into tmp values ('Alcanivorax borkumensis SK2');
insert into tmp values ('Alkalilimnicola ehrlichei MLHE-1');
insert into tmp values ('Alkaliphilus metalliredigens QYMF');
insert into tmp values ('Alkaliphilus oremlandii OhILAs');
insert into tmp values ('Anabaena variabilis ATCC 29413');
insert into tmp values ('Anaeromyxobacter dehalogenans 2CP-C');
insert into tmp values ('Anaeromyxobacter sp. Fw109-5');
insert into tmp values ('Anaplasma marginale str. St. Maries');
insert into tmp values ('Anaplasma phagocytophilum HZ');
insert into tmp values ('Aquifex aeolicus VF5');
insert into tmp values ('Archaeoglobus fulgidus DSM 4304');
insert into tmp values ('Arcobacter butzleri RM4018');
insert into tmp values ('Arthrobacter aurescens TC1');
insert into tmp values ('Arthrobacter sp. FB24');
insert into tmp values ('Aster yellows witches\'-broom phytoplasma AYWB');
insert into tmp values ('Azoarcus sp. BH72');
insert into tmp values ('Azoarcus sp. EbN1');
insert into tmp values ('Azorhizobium caulinodans ORS 571');
insert into tmp values ('Bacillus amyloliquefaciens FZB42');
insert into tmp values ('Bacillus anthracis str. Ames');
insert into tmp values ('Bacillus anthracis str. \'Ames Ancestor\'');
insert into tmp values ('Bacillus anthracis str. Sterne');
insert into tmp values ('Bacillus cereus ATCC 10987');
insert into tmp values ('Bacillus cereus ATCC 14579');
insert into tmp values ('Bacillus cereus E33L');
insert into tmp values ('Bacillus cereus subsp. cytotoxis NVH 391-98');
insert into tmp values ('Bacillus clausii KSM-K16');
insert into tmp values ('Bacillus halodurans C-125');
insert into tmp values ('Bacillus licheniformis ATCC 14580');
insert into tmp values ('Bacillus licheniformis DSM 13');
insert into tmp values ('Bacillus pumilus SAFR-032');
insert into tmp values ('Bacillus subtilis subsp. subtilis str. 168');
insert into tmp values ('Bacillus thuringiensis serovar konkukian str. 97-27');
insert into tmp values ('Bacillus thuringiensis str. Al Hakam');
insert into tmp values ('Bacillus weihenstephanensis KBAB4');
insert into tmp values ('Bacteroides fragilis NCTC 9343');
insert into tmp values ('Bacteroides fragilis YCH46');
insert into tmp values ('Bacteroides thetaiotaomicron VPI-5482');
insert into tmp values ('Bacteroides vulgatus ATCC 8482');
insert into tmp values ('Bartonella bacilliformis KC583');
insert into tmp values ('Bartonella henselae str. Houston-1');
insert into tmp values ('Bartonella quintana str. Toulouse');
insert into tmp values ('Bartonella tribocorum CIP 105476');
insert into tmp values ('Baumannia cicadellinicola str. Hc (Homalodisca coagulata)');
insert into tmp values ('Bdellovibrio bacteriovorus HD100');
insert into tmp values ('Beijerinckia indica subsp. indica ATCC 9039');
insert into tmp values ('Bifidobacterium adolescentis ATCC 15703');
insert into tmp values ('Bifidobacterium longum NCC2705');
insert into tmp values ('Bordetella avium 197N');
insert into tmp values ('Bordetella bronchiseptica RB50');
insert into tmp values ('Bordetella parapertussis 12822');
insert into tmp values ('Bordetella pertussis Tohama I');
insert into tmp values ('Bordetella petrii DSM 12804');
insert into tmp values ('Borrelia afzelii PKo');
insert into tmp values ('Borrelia burgdorferi B31');
insert into tmp values ('Borrelia garinii PBi');
insert into tmp values ('Bradyrhizobium japonicum USDA 110');
insert into tmp values ('Bradyrhizobium sp. BTAi1');
insert into tmp values ('Bradyrhizobium sp. ORS278');
insert into tmp values ('Brucella abortus biovar 1 str. 9-941');
insert into tmp values ('Brucella abortus S19');
insert into tmp values ('Brucella canis ATCC 23365');
insert into tmp values ('Brucella melitensis 16M');
insert into tmp values ('Brucella melitensis biovar Abortus 2308');
insert into tmp values ('Brucella ovis ATCC 25840');
insert into tmp values ('Brucella suis 1330');
insert into tmp values ('Brucella suis ATCC 23445');
insert into tmp values ('Buchnera aphidicola str. APS (Acyrthosiphon pisum)');
insert into tmp values ('Buchnera aphidicola str. Bp (Baizongia pistaciae)');
insert into tmp values ('Buchnera aphidicola str. Cc (Cinara cedri)');
insert into tmp values ('Buchnera aphidicola str. Sg (Schizaphis graminum)');
insert into tmp values ('Burkholderia ambifaria MC40-6');
insert into tmp values ('Burkholderia cenocepacia AU 1054');
insert into tmp values ('Burkholderia cenocepacia HI2424');
insert into tmp values ('Burkholderia cenocepacia MC0-3');
insert into tmp values ('Burkholderia cepacia AMMD');
insert into tmp values ('Burkholderia mallei ATCC 23344');
insert into tmp values ('Burkholderia mallei NCTC 10229');
insert into tmp values ('Burkholderia mallei NCTC 10247');
insert into tmp values ('Burkholderia mallei SAVP1');
insert into tmp values ('Burkholderia multivorans ATCC 17616');
insert into tmp values ('Burkholderia phymatum STM815');
insert into tmp values ('Burkholderia pseudomallei 1106a');
insert into tmp values ('Burkholderia pseudomallei 1710b');
insert into tmp values ('Burkholderia pseudomallei 668');
insert into tmp values ('Burkholderia pseudomallei K96243');
insert into tmp values ('Burkholderia sp. 383');
insert into tmp values ('Burkholderia thailandensis E264');
insert into tmp values ('Burkholderia vietnamiensis G4');
insert into tmp values ('Burkholderia xenovorans LB400');
insert into tmp values ('Caldicellulosiruptor saccharolyticus DSM 8903');
insert into tmp values ('Caldivirga maquilingensis IC-167');
insert into tmp values ('Campylobacter concisus 13826');
insert into tmp values ('Campylobacter curvus 525.92');
insert into tmp values ('Campylobacter fetus subsp. fetus 82-40');
insert into tmp values ('Campylobacter hominis ATCC BAA-381');
insert into tmp values ('Campylobacter jejuni RM1221');
insert into tmp values ('Campylobacter jejuni subsp. doylei 269.97');
insert into tmp values ('Campylobacter jejuni subsp. jejuni 81116');
insert into tmp values ('Campylobacter jejuni subsp. jejuni 81-176');
insert into tmp values ('Campylobacter jejuni subsp. jejuni NCTC 11168');
insert into tmp values ('Candidatus Blochmannia floridanus');
insert into tmp values ('Candidatus Blochmannia pennsylvanicus str. BPEN');
insert into tmp values ('Candidatus Carsonella ruddii PV');
insert into tmp values ('Candidatus Desulfococcus oleovorans Hxd3');
insert into tmp values ('Candidatus Desulforudis audaxviator MP104C');
insert into tmp values ('Candidatus Korarchaeum cryptofilum OPF8');
insert into tmp values ('Candidatus Methanoregula boonei 6A8');
insert into tmp values ('Candidatus Pelagibacter ubique HTCC1062');
insert into tmp values ('Candidatus Protochlamydia amoebophila UWE25');
insert into tmp values ('Candidatus Ruthia magnifica str. Cm (Calyptogena magnifica)');
insert into tmp values ('Candidatus Sulcia muelleri GWSS');
insert into tmp values ('Candidatus Vesicomyosocius okutanii HA');
insert into tmp values ('Carboxydothermus hydrogenoformans Z-2901');
insert into tmp values ('Caulobacter crescentus CB15');
insert into tmp values ('Caulobacter sp. K31');
insert into tmp values ('Chlamydia muridarum Nigg');
insert into tmp values ('Chlamydia trachomatis 434 Bu');
insert into tmp values ('Chlamydia trachomatis A HAR-13');
insert into tmp values ('Chlamydia trachomatis D UW-3 CX');
insert into tmp values ('Chlamydia trachomatis L2b UCH-1 proctitis');
insert into tmp values ('Chlamydophila abortus S26 3');
insert into tmp values ('Chlamydophila caviae GPIC');
insert into tmp values ('Chlamydophila felis Fe C-56');
insert into tmp values ('Chlamydophila pneumoniae AR39');
insert into tmp values ('Chlamydophila pneumoniae CWL029');
insert into tmp values ('Chlamydophila pneumoniae J138');
insert into tmp values ('Chlamydophila pneumoniae TW-183');
insert into tmp values ('Chlorobium chlorochromatii CaD3');
insert into tmp values ('Chlorobium phaeobacteroides DSM 266');
insert into tmp values ('Chlorobium tepidum TLS');
insert into tmp values ('Chloroflexus aurantiacus J-10-fl');
insert into tmp values ('Chromobacterium violaceum ATCC 12472');
insert into tmp values ('Chromohalobacter salexigens DSM 3043');
insert into tmp values ('Citrobacter koseri ATCC BAA-895');
insert into tmp values ('Clavibacter michiganensis subsp. michiganensis NCPPB 382');
insert into tmp values ('Clavibacter michiganensis subsp. sepedonicus');
insert into tmp values ('Clostridium acetobutylicum ATCC 824');
insert into tmp values ('Clostridium beijerinckii NCIMB 8052');
insert into tmp values ('Clostridium botulinum A3 str. Loch Maree');
insert into tmp values ('Clostridium botulinum A str. ATCC 19397');
insert into tmp values ('Clostridium botulinum A str. ATCC 3502');
insert into tmp values ('Clostridium botulinum A str. Hall');
insert into tmp values ('Clostridium botulinum B1 str. Okra');
insert into tmp values ('Clostridium botulinum B str. Eklund 17B');
insert into tmp values ('Clostridium botulinum F str. Langeland');
insert into tmp values ('Clostridium difficile 630');
insert into tmp values ('Clostridium kluyveri DSM 555');
insert into tmp values ('Clostridium novyi NT');
insert into tmp values ('Clostridium perfringens ATCC 13124');
insert into tmp values ('Clostridium perfringens SM101');
insert into tmp values ('Clostridium perfringens str. 13');
insert into tmp values ('Clostridium phytofermentans ISDg');
insert into tmp values ('Clostridium tetani E88');
insert into tmp values ('Clostridium thermocellum ATCC 27405');
insert into tmp values ('Colwellia psychrerythraea 34H');
insert into tmp values ('Corynebacterium diphtheriae NCTC 13129');
insert into tmp values ('Corynebacterium efficiens YS-314');
insert into tmp values ('Corynebacterium glutamicum ATCC 13032');
insert into tmp values ('Corynebacterium glutamicum ATCC 13032 Kitasato');
insert into tmp values ('Corynebacterium glutamicum R');
insert into tmp values ('Corynebacterium jeikeium K411');
insert into tmp values ('Corynebacterium urealyticum DSM 7109');
insert into tmp values ('Coxiella burnetii Dugway 5J108-111');
insert into tmp values ('Coxiella burnetii RSA 331');
insert into tmp values ('Coxiella burnetii RSA 493');
insert into tmp values ('Cupriavidus taiwanensis');
insert into tmp values ('Cyanothece sp. ATCC 51142');
insert into tmp values ('Cytophaga hutchinsonii ATCC 33406');
insert into tmp values ('Dechloromonas aromatica RCB');
insert into tmp values ('Dehalococcoides ethenogenes 195');
insert into tmp values ('Dehalococcoides sp. BAV1');
insert into tmp values ('Dehalococcoides sp. CBDB1');
insert into tmp values ('Deinococcus geothermalis DSM 11300');
insert into tmp values ('Deinococcus radiodurans R1');
insert into tmp values ('Delftia acidovorans SPH-1');
insert into tmp values ('Desulfitobacterium hafniense Y51');
insert into tmp values ('Desulfotalea psychrophila LSv54');
insert into tmp values ('Desulfotomaculum reducens MI-1');
insert into tmp values ('Desulfovibrio desulfuricans G20');
insert into tmp values ('Desulfovibrio vulgaris subsp. vulgaris DP4');
insert into tmp values ('Desulfovibrio vulgaris subsp. vulgaris str. Hildenborough');
insert into tmp values ('Dichelobacter nodosus VCS1703A');
insert into tmp values ('Dinoroseobacter shibae DFL 12');
insert into tmp values ('Ehrlichia canis str. Jake');
insert into tmp values ('Ehrlichia chaffeensis str. Arkansas');
insert into tmp values ('Ehrlichia ruminantium str. Gardel');
insert into tmp values ('Ehrlichia ruminantium str. Welgevonden');
insert into tmp values ('Ehrlichia ruminantium Welgevonden');
insert into tmp values ('Enterobacter sakazakii ATCC BAA-894');
insert into tmp values ('Enterobacter sp. 638');
insert into tmp values ('Enterococcus faecalis V583');
insert into tmp values ('Erwinia carotovora subsp. atroseptica SCRI1043');
insert into tmp values ('Erythrobacter litoralis HTCC2594');
insert into tmp values ('Escherichia coli 536');
insert into tmp values ('Escherichia coli APEC O1');
insert into tmp values ('Escherichia coli ATCC 8739');
insert into tmp values ('Escherichia coli CFT073');
insert into tmp values ('Escherichia coli E24377A');
insert into tmp values ('Escherichia coli HS');
insert into tmp values ('Escherichia coli O157:H7 EDL933');
insert into tmp values ('Escherichia coli O157:H7 str. Sakai');
insert into tmp values ('Escherichia coli SECEC SMS-3-5');
insert into tmp values ('Escherichia coli str. K-12 substr. DH10B');
insert into tmp values ('Escherichia coli str. K-12 substr. MG1655');
insert into tmp values ('Escherichia coli UTI89');
insert into tmp values ('Escherichia coli W3110 DNA');
insert into tmp values ('Exiguobacterium sibiricum 255-15');
insert into tmp values ('Fervidobacterium nodosum Rt17-B1');
insert into tmp values ('Finegoldia magna ATCC 29328');
insert into tmp values ('Flavobacterium johnsoniae UW101');
insert into tmp values ('Flavobacterium psychrophilum JIP02 86');
insert into tmp values ('Francisella philomiragia subsp. philomiragia ATCC 25017');
insert into tmp values ('Francisella tularensis subsp. holarctica');
insert into tmp values ('Francisella tularensis subsp. holarctica FTNF002-00');
insert into tmp values ('Francisella tularensis subsp. holarctica OSU18');
insert into tmp values ('Francisella tularensis subsp. mediasiatica FSC147');
insert into tmp values ('Francisella tularensis subsp. novicida U112');
insert into tmp values ('Francisella tularensis subsp. tularensis FSC198');
insert into tmp values ('Francisella tularensis subsp. tularensis Schu 4');
insert into tmp values ('Francisella tularensis subsp. tularensis WY96-3418');
insert into tmp values ('Frankia alni ACN14a');
insert into tmp values ('Frankia sp. CcI3');
insert into tmp values ('Frankia sp. EAN1pec');
insert into tmp values ('Fusobacterium nucleatum subsp. nucleatum ATCC 25586');
insert into tmp values ('Geobacillus kaustophilus HTA426');
insert into tmp values ('Geobacillus thermodenitrificans NG80-2');
insert into tmp values ('Geobacter metallireducens GS-15');
insert into tmp values ('Geobacter sulfurreducens PCA');
insert into tmp values ('Geobacter uraniireducens Rf4');
insert into tmp values ('Gloeobacter violaceus PCC 7421');
insert into tmp values ('Gluconacetobacter diazotrophicus PAl 5');
insert into tmp values ('Gluconobacter oxydans 621H');
insert into tmp values ('Gramella forsetii KT0803');
insert into tmp values ('Granulibacter bethesdensis CGDNIH1');
insert into tmp values ('Haemophilus ducreyi 35000HP');
insert into tmp values ('Haemophilus influenzae 86-028NP');
insert into tmp values ('Haemophilus influenzae PittEE');
insert into tmp values ('Haemophilus influenzae PittGG');
insert into tmp values ('Haemophilus influenzae Rd KW20');
insert into tmp values ('Haemophilus somnus 129PT');
insert into tmp values ('Haemophilus somnus 2336');
insert into tmp values ('Hahella chejuensis KCTC 2396');
insert into tmp values ('Haloarcula marismortui ATCC 43049');
insert into tmp values ('Halobacterium salinarum R1');
insert into tmp values ('Halobacterium sp. NRC-1');
insert into tmp values ('Haloquadratum walsbyi DSM 16790');
insert into tmp values ('Halorhodospira halophila SL1');
insert into tmp values ('Helicobacter acinonychis str. Sheeba');
insert into tmp values ('Helicobacter hepaticus ATCC 51449');
insert into tmp values ('Helicobacter pylori 26695');
insert into tmp values ('Helicobacter pylori HPAG1');
insert into tmp values ('Helicobacter pylori J99');
insert into tmp values ('Heliobacterium modesticaldum Ice1');
insert into tmp values ('Herminiimonas arsenicoxydans');
insert into tmp values ('Herpetosiphon aurantiacus ATCC 23779');
insert into tmp values ('Hyperthermus butylicus DSM 5456');
insert into tmp values ('Hyphomonas neptunium ATCC 15444');
insert into tmp values ('Idiomarina loihiensis L2TR');
insert into tmp values ('Ignicoccus hospitalis KIN4 I');
insert into tmp values ('Jannaschia sp. CCS1');
insert into tmp values ('Janthinobacterium sp. Marseille');
insert into tmp values ('Kineococcus radiotolerans SRS30216');
insert into tmp values ('Klebsiella pneumoniae subsp. pneumoniae MGH 78578');
insert into tmp values ('Lactobacillus acidophilus NCFM');
insert into tmp values ('Lactobacillus brevis ATCC 367');
insert into tmp values ('Lactobacillus casei ATCC 334');
insert into tmp values ('Lactobacillus delbrueckii subsp. bulgaricus ATCC 11842');
insert into tmp values ('Lactobacillus delbrueckii subsp. bulgaricus ATCC BAA-365');
insert into tmp values ('Lactobacillus fermentum IFO 3956');
insert into tmp values ('Lactobacillus gasseri ATCC 33323');
insert into tmp values ('Lactobacillus helveticus DPC 4571');
insert into tmp values ('Lactobacillus johnsonii NCC 533');
insert into tmp values ('Lactobacillus plantarum WCFS1');
insert into tmp values ('Lactobacillus reuteri F275');
insert into tmp values ('Lactobacillus sakei subsp. sakei 23K');
insert into tmp values ('Lactobacillus salivarius UCC118');
insert into tmp values ('Lactococcus lactis subsp. cremoris MG1363');
insert into tmp values ('Lactococcus lactis subsp. cremoris SK11');
insert into tmp values ('Lactococcus lactis subsp. lactis Il1403');
insert into tmp values ('Lawsonia intracellularis PHE MN1-00');
insert into tmp values ('Legionella pneumophila str. Corby');
insert into tmp values ('Legionella pneumophila str. Lens');
insert into tmp values ('Legionella pneumophila str. Paris');
insert into tmp values ('Legionella pneumophila subsp. pneumophila str. Philadelphia 1');
insert into tmp values ('Leifsonia xyli subsp. xyli str. CTCB07');
insert into tmp values ('Leptospira biflexa serovar Patoc strain \'Patoc 1 (Paris)\'');
insert into tmp values ('Leptospira borgpetersenii serovar Hardjo-bovis JB197');
insert into tmp values ('Leptospira borgpetersenii serovar Hardjo-bovis L550');
insert into tmp values ('Leptospira interrogans serovar Copenhageni str. Fiocruz L1-130');
insert into tmp values ('Leptospira interrogans serovar Lai str. 56601');
insert into tmp values ('Leptothrix cholodnii SP-6');
insert into tmp values ('Leuconostoc citreum KM20');
insert into tmp values ('Leuconostoc mesenteroides subsp. mesenteroides ATCC 8293');
insert into tmp values ('Listeria innocua Clip11262');
insert into tmp values ('Listeria monocytogenes EGD-e');
insert into tmp values ('Listeria monocytogenes str. 4b F2365');
insert into tmp values ('Listeria welshimeri serovar 6b str. SLCC5334');
insert into tmp values ('Lysinibacillus sphaericus C3-41');
insert into tmp values ('Magnetococcus sp. MC-1');
insert into tmp values ('Magnetospirillum magneticum AMB-1');
insert into tmp values ('Mannheimia succiniciproducens MBEL55E');
insert into tmp values ('Maricaulis maris MCS10');
insert into tmp values ('Marinobacter aquaeolei VT8');
insert into tmp values ('Marinomonas sp. MWYL1');
insert into tmp values ('Mesoplasma florum L1');
insert into tmp values ('Mesorhizobium loti MAFF303099');
insert into tmp values ('Mesorhizobium sp. BNC1');
insert into tmp values ('Metallosphaera sedula DSM 5348');
insert into tmp values ('Methanobrevibacter smithii ATCC 35061');
insert into tmp values ('Methanocaldococcus jannaschii DSM 2661');
insert into tmp values ('Methanococcoides burtonii DSM 6242');
insert into tmp values ('Methanococcus aeolicus Nankai-3');
insert into tmp values ('Methanococcus maripaludis C5');
insert into tmp values ('Methanococcus maripaludis C6');
insert into tmp values ('Methanococcus maripaludis C7');
insert into tmp values ('Methanococcus maripaludis S2');
insert into tmp values ('Methanococcus vannielii SB');
insert into tmp values ('Methanocorpusculum labreanum Z');
insert into tmp values ('Methanoculleus marisnigri JR1');
insert into tmp values ('Methanopyrus kandleri AV19');
insert into tmp values ('Methanosaeta thermophila PT');
insert into tmp values ('Methanosarcina acetivorans C2A');
insert into tmp values ('Methanosarcina barkeri str. fusaro');
insert into tmp values ('Methanosarcina mazei Go1');
insert into tmp values ('Methanosphaera stadtmanae DSM 3091');
insert into tmp values ('Methanospirillum hungatei JF-1');
insert into tmp values ('Methanothermobacter thermautotrophicus str. Delta H');
insert into tmp values ('Methylibium petroleiphilum PM1');
insert into tmp values ('Methylobacillus flagellatus KT');
insert into tmp values ('Methylobacterium extorquens PA1');
insert into tmp values ('Methylobacterium radiotolerans JCM 2831');
insert into tmp values ('Methylobacterium sp. 4-46');
insert into tmp values ('Methylococcus capsulatus str. Bath');
insert into tmp values ('Microcystis aeruginosa NIES-843');
insert into tmp values ('Moorella thermoacetica ATCC 39073');
insert into tmp values ('Mycobacterium abscessus');
insert into tmp values ('Mycobacterium avium 104');
insert into tmp values ('Mycobacterium avium subsp. paratuberculosis K-10');
insert into tmp values ('Mycobacterium bovis AF2122 97');
insert into tmp values ('Mycobacterium bovis BCG str. Pasteur 1173P2');
insert into tmp values ('Mycobacterium gilvum PYR-GCK');
insert into tmp values ('Mycobacterium leprae TN');
insert into tmp values ('Mycobacterium marinum M');
insert into tmp values ('Mycobacterium smegmatis str. MC2 155');
insert into tmp values ('Mycobacterium sp. JLS');
insert into tmp values ('Mycobacterium sp. KMS');
insert into tmp values ('Mycobacterium sp. MCS');
insert into tmp values ('Mycobacterium tuberculosis CDC1551');
insert into tmp values ('Mycobacterium tuberculosis F11');
insert into tmp values ('Mycobacterium tuberculosis H37Ra');
insert into tmp values ('Mycobacterium tuberculosis H37Rv');
insert into tmp values ('Mycobacterium ulcerans Agy99');
insert into tmp values ('Mycobacterium vanbaalenii PYR-1');
insert into tmp values ('Mycoplasma agalactiae PG2');
insert into tmp values ('Mycoplasma capricolum subsp. capricolum ATCC 27343');
insert into tmp values ('Mycoplasma gallisepticum R');
insert into tmp values ('Mycoplasma genitalium G37');
insert into tmp values ('Mycoplasma hyopneumoniae 232');
insert into tmp values ('Mycoplasma hyopneumoniae 7448');
insert into tmp values ('Mycoplasma hyopneumoniae J');
insert into tmp values ('Mycoplasma mobile 163K');
insert into tmp values ('Mycoplasma mycoides subsp. mycoides SC str. PG1');
insert into tmp values ('Mycoplasma penetrans HF-2');
insert into tmp values ('Mycoplasma pneumoniae M129');
insert into tmp values ('Mycoplasma pulmonis UAB CTIP');
insert into tmp values ('Mycoplasma synoviae 53');
insert into tmp values ('Myxococcus xanthus DK 1622');
insert into tmp values ('Nanoarchaeum equitans Kin4-M');
insert into tmp values ('Natronomonas pharaonis DSM 2160');
insert into tmp values ('Neisseria gonorrhoeae FA 1090');
insert into tmp values ('Neisseria meningitidis 053442');
insert into tmp values ('Neisseria meningitidis FAM18');
insert into tmp values ('Neisseria meningitidis MC58');
insert into tmp values ('Neisseria meningitidis Z2491');
insert into tmp values ('Neorickettsia sennetsu str. Miyayama');
insert into tmp values ('Nitratiruptor sp. SB155-2');
insert into tmp values ('Nitrobacter hamburgensis X14');
insert into tmp values ('Nitrobacter winogradskyi Nb-255');
insert into tmp values ('Nitrosococcus oceani ATCC 19707');
insert into tmp values ('Nitrosomonas europaea ATCC 19718');
insert into tmp values ('Nitrosomonas eutropha C91');
insert into tmp values ('Nitrosopumilus maritimus SCM1');
insert into tmp values ('Nitrosospira multiformis ATCC 25196');
insert into tmp values ('Nocardia farcinica IFM 10152');
insert into tmp values ('Nocardioides sp. JS614');
insert into tmp values ('Nostoc sp. PCC 7120');
insert into tmp values ('Novosphingobium aromaticivorans DSM 12444');
insert into tmp values ('Oceanobacillus iheyensis HTE831');
insert into tmp values ('Ochrobactrum anthropi ATCC 49188');
insert into tmp values ('Oenococcus oeni PSU-1');
insert into tmp values ('Onion yellows phytoplasma OY-M');
insert into tmp values ('Opitutus terrae PB90-1');
insert into tmp values ('Orientia tsutsugamushi Boryong');
insert into tmp values ('Orientia tsutsugamushi str. Ikeda');
insert into tmp values ('Parabacteroides distasonis ATCC 8503');
insert into tmp values ('Paracoccus denitrificans PD1222');
insert into tmp values ('Parvibaculum lavamentivorans DS-1');
insert into tmp values ('Pasteurella multocida subsp. multocida str. Pm70');
insert into tmp values ('Pediococcus pentosaceus ATCC 25745');
insert into tmp values ('Pelobacter carbinolicus DSM 2380');
insert into tmp values ('Pelobacter propionicus DSM 2379');
insert into tmp values ('Pelodictyon luteolum DSM 273');
insert into tmp values ('Pelotomaculum thermopropionicum SI');
insert into tmp values ('Petrotoga mobilis SJ95');
insert into tmp values ('Photobacterium profundum SS9');
insert into tmp values ('Photorhabdus luminescens subsp. laumondii TTO1');
insert into tmp values ('Picrophilus torridus DSM 9790');
insert into tmp values ('Polaromonas naphthalenivorans CJ2');
insert into tmp values ('Polaromonas sp. JS666');
insert into tmp values ('Polynucleobacter necessarius STIR1');
insert into tmp values ('Polynucleobacter sp. QLW-P1DMWA-1');
insert into tmp values ('Porphyromonas gingivalis W83');
insert into tmp values ('Prochlorococcus marinus str. AS9601');
insert into tmp values ('Prochlorococcus marinus str. MIT 9211');
insert into tmp values ('Prochlorococcus marinus str. MIT 9215');
insert into tmp values ('Prochlorococcus marinus str. MIT 9301');
insert into tmp values ('Prochlorococcus marinus str. MIT 9303');
insert into tmp values ('Prochlorococcus marinus str. MIT 9312');
insert into tmp values ('Prochlorococcus marinus str. MIT 9313');
insert into tmp values ('Prochlorococcus marinus str. MIT 9515');
insert into tmp values ('Prochlorococcus marinus str. NATL1A');
insert into tmp values ('Prochlorococcus marinus str. NATL2A');
insert into tmp values ('Prochlorococcus marinus subsp. marinus str. CCMP1375');
insert into tmp values ('Prochlorococcus marinus subsp. pastoris str. CCMP1986');
insert into tmp values ('Propionibacterium acnes KPA171202');
insert into tmp values ('Prosthecochloris vibrioformis DSM 265');
insert into tmp values ('Pseudoalteromonas atlantica T6c');
insert into tmp values ('Pseudoalteromonas haloplanktis TAC125');
insert into tmp values ('Pseudomonas aeruginosa PA7');
insert into tmp values ('Pseudomonas aeruginosa PAO1');
insert into tmp values ('Pseudomonas aeruginosa UCBPP-PA14');
insert into tmp values ('Pseudomonas entomophila L48');
insert into tmp values ('Pseudomonas fluorescens Pf-5');
insert into tmp values ('Pseudomonas fluorescens PfO-1');
insert into tmp values ('Pseudomonas mendocina ymp');
insert into tmp values ('Pseudomonas putida F1');
insert into tmp values ('Pseudomonas putida GB-1');
insert into tmp values ('Pseudomonas putida KT2440');
insert into tmp values ('Pseudomonas putida W619');
insert into tmp values ('Pseudomonas stutzeri A1501');
insert into tmp values ('Pseudomonas syringae pv. phaseolicola 1448A');
insert into tmp values ('Pseudomonas syringae pv. syringae B728a');
insert into tmp values ('Pseudomonas syringae pv. tomato str. DC3000');
insert into tmp values ('Psychrobacter arcticus 273-4');
insert into tmp values ('Psychrobacter cryohalolentis K5');
insert into tmp values ('Psychrobacter sp. PRwf-1');
insert into tmp values ('Psychromonas ingrahamii 37');
insert into tmp values ('Pyrobaculum aerophilum str. IM2');
insert into tmp values ('Pyrobaculum arsenaticum DSM 13514');
insert into tmp values ('Pyrobaculum calidifontis JCM 11548');
insert into tmp values ('Pyrobaculum islandicum DSM 4184');
insert into tmp values ('Pyrococcus abyssi GE5');
insert into tmp values ('Pyrococcus furiosus DSM 3638');
insert into tmp values ('Pyrococcus horikoshii OT3');
insert into tmp values ('Ralstonia eutropha H16');
insert into tmp values ('Ralstonia eutropha JMP134 mega');
insert into tmp values ('Ralstonia metallidurans CH34');
insert into tmp values ('Ralstonia solanacearum GMI1000');
insert into tmp values ('Renibacterium salmoninarum ATCC 33209');
insert into tmp values ('Rhizobium etli CFN 42');
insert into tmp values ('Rhizobium leguminosarum bv. viciae 3841');
insert into tmp values ('Rhodobacter sphaeroides 2.4.1');
insert into tmp values ('Rhodobacter sphaeroides ATCC 17025');
insert into tmp values ('Rhodobacter sphaeroides ATCC 17029');
insert into tmp values ('Rhodococcus sp. RHA1');
insert into tmp values ('Rhodoferax ferrireducens T118');
insert into tmp values ('Rhodopirellula baltica SH 1');
insert into tmp values ('Rhodopseudomonas palustris BisA53');
insert into tmp values ('Rhodopseudomonas palustris BisB18');
insert into tmp values ('Rhodopseudomonas palustris BisB5');
insert into tmp values ('Rhodopseudomonas palustris CGA009');
insert into tmp values ('Rhodopseudomonas palustris HaA2');
insert into tmp values ('Rhodospirillum rubrum ATCC 11170');
insert into tmp values ('Rickettsia akari str. Hartford');
insert into tmp values ('Rickettsia bellii OSU 85-389');
insert into tmp values ('Rickettsia bellii RML369-C');
insert into tmp values ('Rickettsia canadensis str. McKiel');
insert into tmp values ('Rickettsia conorii str. Malish 7');
insert into tmp values ('Rickettsia felis URRWXCal2');
insert into tmp values ('Rickettsia massiliae MTU5');
insert into tmp values ('Rickettsia prowazekii str. Madrid E');
insert into tmp values ('Rickettsia rickettsii str. Iowa');
insert into tmp values ('Rickettsia rickettsii str. \'Sheila Smith\'');
insert into tmp values ('Rickettsia typhi str. Wilmington');
insert into tmp values ('Roseiflexus castenholzii DSM 13941');
insert into tmp values ('Roseiflexus sp. RS-1');
insert into tmp values ('Roseobacter denitrificans OCh 114');
insert into tmp values ('Rubrobacter xylanophilus DSM 9941');
insert into tmp values ('Saccharophagus degradans 2-40');
insert into tmp values ('Saccharopolyspora erythraea NRRL 2338');
insert into tmp values ('Salinibacter ruber DSM 13855');
insert into tmp values ('Salinispora arenicola CNS-205');
insert into tmp values ('Salinispora tropica CNB-440');
insert into tmp values ('Salmonella enterica subsp. arizonae serovar 62:z4');
insert into tmp values ('Salmonella enterica subsp. enterica serovar Choleraesuis str. SC-B67');
insert into tmp values ('Salmonella enterica subsp. enterica serovar Paratyphi A str. ATCC 9150');
insert into tmp values ('Salmonella enterica subsp. enterica serovar Paratyphi B str. SPB7');
insert into tmp values ('Salmonella enterica subsp. enterica serovar Typhi str. CT18');
insert into tmp values ('Salmonella enterica subsp. enterica serovar Typhi Ty2');
insert into tmp values ('Salmonella typhimurium LT2');
insert into tmp values ('Serratia proteamaculans 568');
insert into tmp values ('Shewanella amazonensis SB2B');
insert into tmp values ('Shewanella baltica OS155');
insert into tmp values ('Shewanella baltica OS185');
insert into tmp values ('Shewanella baltica OS195');
insert into tmp values ('Shewanella denitrificans OS217');
insert into tmp values ('Shewanella frigidimarina NCIMB 400');
insert into tmp values ('Shewanella halifaxensis HAW-EB4');
insert into tmp values ('Shewanella loihica PV-4');
insert into tmp values ('Shewanella oneidensis MR-1');
insert into tmp values ('Shewanella pealeana ATCC 700345');
insert into tmp values ('Shewanella putrefaciens CN-32');
insert into tmp values ('Shewanella sediminis HAW-EB3');
insert into tmp values ('Shewanella sp. ANA-3');
insert into tmp values ('Shewanella sp. MR-4');
insert into tmp values ('Shewanella sp. MR-7');
insert into tmp values ('Shewanella sp. W3-18-1');
insert into tmp values ('Shewanella woodyi ATCC 51908');
insert into tmp values ('Shigella boydii CDC 3083-94');
insert into tmp values ('Shigella boydii Sb227');
insert into tmp values ('Shigella dysenteriae Sd197');
insert into tmp values ('Shigella flexneri 2a str. 2457T');
insert into tmp values ('Shigella flexneri 2a str. 301');
insert into tmp values ('Shigella flexneri 5 str. 8401');
insert into tmp values ('Shigella sonnei Ss046');
insert into tmp values ('Silicibacter pomeroyi DSS-3');
insert into tmp values ('Silicibacter sp. TM1040');
insert into tmp values ('Sinorhizobium medicae WSM419');
insert into tmp values ('Sinorhizobium meliloti 1021');
insert into tmp values ('Sodalis glossinidius str. \'morsitans\'');
insert into tmp values ('Solibacter usitatus Ellin6076');
insert into tmp values ('Sorangium cellulosum \'So ce 56\'');
insert into tmp values ('Sphingomonas wittichii RW1');
insert into tmp values ('Sphingopyxis alaskensis RB2256');
insert into tmp values ('Staphylococcus aureus RF122');
insert into tmp values ('Staphylococcus aureus subsp. aureus COL');
insert into tmp values ('Staphylococcus aureus subsp. aureus JH1');
insert into tmp values ('Staphylococcus aureus subsp. aureus JH9');
insert into tmp values ('Staphylococcus aureus subsp. aureus MRSA252');
insert into tmp values ('Staphylococcus aureus subsp. aureus MSSA476');
insert into tmp values ('Staphylococcus aureus subsp. aureus Mu3');
insert into tmp values ('Staphylococcus aureus subsp. aureus Mu50');
insert into tmp values ('Staphylococcus aureus subsp. aureus MW2');
insert into tmp values ('Staphylococcus aureus subsp. aureus N315');
insert into tmp values ('Staphylococcus aureus subsp. aureus NCTC 8325');
insert into tmp values ('Staphylococcus aureus subsp. aureus str. Newman');
insert into tmp values ('Staphylococcus aureus subsp. aureus USA300');
insert into tmp values ('Staphylococcus aureus subsp. aureus USA300 TCH1516');
insert into tmp values ('Staphylococcus epidermidis ATCC 12228');
insert into tmp values ('Staphylococcus epidermidis RP62A');
insert into tmp values ('Staphylococcus haemolyticus JCSC1435');
insert into tmp values ('Staphylococcus saprophyticus subsp. saprophyticus ATCC 15305');
insert into tmp values ('Staphylothermus marinus F1');
insert into tmp values ('Streptococcus agalactiae 2603V R');
insert into tmp values ('Streptococcus agalactiae A909');
insert into tmp values ('Streptococcus agalactiae NEM316');
insert into tmp values ('Streptococcus gordonii str. Challis substr. CH1');
insert into tmp values ('Streptococcus mutans UA159');
insert into tmp values ('Streptococcus pneumoniae CGSP14');
insert into tmp values ('Streptococcus pneumoniae D39');
insert into tmp values ('Streptococcus pneumoniae Hungary19A-6');
insert into tmp values ('Streptococcus pneumoniae R6');
insert into tmp values ('Streptococcus pneumoniae TIGR4');
insert into tmp values ('Streptococcus pyogenes M1 GAS');
insert into tmp values ('Streptococcus pyogenes MGAS10270');
insert into tmp values ('Streptococcus pyogenes MGAS10394');
insert into tmp values ('Streptococcus pyogenes MGAS10750');
insert into tmp values ('Streptococcus pyogenes MGAS2096');
insert into tmp values ('Streptococcus pyogenes MGAS315');
insert into tmp values ('Streptococcus pyogenes MGAS5005');
insert into tmp values ('Streptococcus pyogenes MGAS6180');
insert into tmp values ('Streptococcus pyogenes MGAS8232');
insert into tmp values ('Streptococcus pyogenes MGAS9429');
insert into tmp values ('Streptococcus pyogenes SSI-1');
insert into tmp values ('Streptococcus pyogenes str. Manfredo');
insert into tmp values ('Streptococcus sanguinis SK36');
insert into tmp values ('Streptococcus suis 05ZYH33');
insert into tmp values ('Streptococcus suis 98HAH33');
insert into tmp values ('Streptococcus thermophilus CNRZ1066');
insert into tmp values ('Streptococcus thermophilus LMD-9');
insert into tmp values ('Streptococcus thermophilus LMG 18311');
insert into tmp values ('Streptomyces avermitilis MA-4680');
insert into tmp values ('Streptomyces coelicolor A3(2)');
insert into tmp values ('Streptomyces griseus subsp. griseus NBRC 13350');
insert into tmp values ('Sulfolobus acidocaldarius DSM 639');
insert into tmp values ('Sulfolobus solfataricus P2');
insert into tmp values ('Sulfolobus tokodaii str. 7');
insert into tmp values ('Sulfurimonas denitrificans DSM 1251');
insert into tmp values ('Sulfurovum sp. NBC37-1');
insert into tmp values ('Symbiobacterium thermophilum IAM 14863');
insert into tmp values ('Synechococcus elongatus PCC 6301');
insert into tmp values ('Synechococcus elongatus PCC 7942');
insert into tmp values ('Synechococcus sp. CC9311');
insert into tmp values ('Synechococcus sp. CC9605');
insert into tmp values ('Synechococcus sp. CC9902');
insert into tmp values ('Synechococcus sp. JA-2-3B\'a(2-13)');
insert into tmp values ('Synechococcus sp. JA-3-3Ab');
insert into tmp values ('Synechococcus sp. PCC 7002');
insert into tmp values ('Synechococcus sp. RCC307');
insert into tmp values ('Synechococcus sp. WH 7803');
insert into tmp values ('Synechococcus sp. WH 8102');
insert into tmp values ('Synechocystis sp. PCC 6803');
insert into tmp values ('Syntrophobacter fumaroxidans MPOB');
insert into tmp values ('Syntrophomonas wolfei subsp. wolfei str. Goettingen');
insert into tmp values ('Syntrophus aciditrophicus SB');
insert into tmp values ('Thermoanaerobacter pseudethanolicus ATCC 33223');
insert into tmp values ('Thermoanaerobacter sp. X514');
insert into tmp values ('Thermoanaerobacter tengcongensis MB4');
insert into tmp values ('Thermobifida fusca YX');
insert into tmp values ('Thermococcus kodakarensis KOD1');
insert into tmp values ('Thermofilum pendens Hrk 5');
insert into tmp values ('Thermoplasma acidophilum DSM 1728');
insert into tmp values ('Thermoplasma volcanium GSS1');
insert into tmp values ('Thermoproteus neutrophilus V24Sta');
insert into tmp values ('Thermosipho melanesiensis BI429');
insert into tmp values ('Thermosynechococcus elongatus BP-1');
insert into tmp values ('Thermotoga lettingae TMO');
insert into tmp values ('Thermotoga maritima MSB8');
insert into tmp values ('Thermotoga petrophila RKU-1');
insert into tmp values ('Thermotoga sp. RQ2');
insert into tmp values ('Thermus thermophilus HB27');
insert into tmp values ('Thermus thermophilus HB8');
insert into tmp values ('Thiobacillus denitrificans ATCC 25259');
insert into tmp values ('Thiomicrospira crunogena XCL-2');
insert into tmp values ('Treponema denticola ATCC 35405');
insert into tmp values ('Treponema pallidum subsp. pallidum str. Nichols');
insert into tmp values ('Trichodesmium erythraeum IMS101');
insert into tmp values ('Tropheryma whipplei str. Twist');
insert into tmp values ('Tropheryma whipplei TW08 27');
insert into tmp values ('Uncultured methanogenic archaeon RC-I');
insert into tmp values ('Ureaplasma parvum serovar 3 str. ATCC 27815');
insert into tmp values ('Ureaplasma parvum serovar 3 str. ATCC 700970');
insert into tmp values ('Verminephrobacter eiseniae EF01-2');
insert into tmp values ('Vibrio cholerae O1 biovar eltor str. N16961');
insert into tmp values ('Vibrio cholerae O395');
insert into tmp values ('Vibrio fischeri ES114');
insert into tmp values ('Vibrio harveyi ATCC BAA-1116');
insert into tmp values ('Vibrio parahaemolyticus RIMD 2210633');
insert into tmp values ('Vibrio vulnificus CMCP6');
insert into tmp values ('Vibrio vulnificus YJ016');
insert into tmp values ('Wigglesworthia glossinidia endosymbiont of Glossina brevipalpis');
insert into tmp values ('Wolbachia endosymbiont of Drosophila melanogaster');
insert into tmp values ('Wolbachia endosymbiont strain TRS of Brugia malayi');
insert into tmp values ('Wolinella succinogenes DSM 1740');
insert into tmp values ('Xanthobacter autotrophicus Py2');
insert into tmp values ('Xanthomonas axonopodis pv. citri str. 306');
insert into tmp values ('Xanthomonas campestris pv. campestris str. 8004');
insert into tmp values ('Xanthomonas campestris pv. campestris str. ATCC 33913');
insert into tmp values ('Xanthomonas campestris pv. vesicatoria str. 85-10');
insert into tmp values ('Xanthomonas oryzae pv. oryzae KACC10331');
insert into tmp values ('Xanthomonas oryzae pv. oryzae MAFF 311018');
insert into tmp values ('Xylella fastidiosa 9a5c');
insert into tmp values ('Xylella fastidiosa M12');
insert into tmp values ('Xylella fastidiosa M23');
insert into tmp values ('Xylella fastidiosa Temecula1');
insert into tmp values ('Yersinia enterocolitica subsp. enterocolitica 8081');
insert into tmp values ('Yersinia pestis Angola');
insert into tmp values ('Yersinia pestis Antiqua');
insert into tmp values ('Yersinia pestis biovar Microtus str. 91001');
insert into tmp values ('Yersinia pestis CO92');
insert into tmp values ('Yersinia pestis KIM');
insert into tmp values ('Yersinia pestis Nepal516');
insert into tmp values ('Yersinia pestis Pestoides F');
insert into tmp values ('Yersinia pseudotuberculosis IP 31758');
insert into tmp values ('Yersinia pseudotuberculosis IP 32953');
insert into tmp values ('Yersinia pseudotuberculosis YPIII');
insert into tmp values ('Zymomonas mobilis subsp. mobilis ZM4');

select name_txt, tax_id from tmp LEFT OUTER JOIN names USING (name_txt) where tax_id is null;
