# here we create a table listing all genome names for full bacterial genomes from NCBI as of 2008-06-05
# the directory names use underscores instead of spaces; we fix that
# then we can check which of these names do not exist in the NCBI taxonomy names table

use ncbi_taxonomy;
drop table if exists tmp;
create table tmp (name_txt varchar(255));

insert into tmp values ('Acaryochloris marina MBIC11017');
insert into tmp values ('Acholeplasma laidlawii PG 8A');
insert into tmp values ('Acidiphilium cryptum JF-5');
insert into tmp values ('Acidobacteria bacterium Ellin345');
insert into tmp values ('Acidothermus cellulolyticus 11B');
insert into tmp values ('Acidovorax avenae citrulli AAC00-1');
insert into tmp values ('Acidovorax JS42');
insert into tmp values ('Acinetobacter baumannii ATCC 17978');
insert into tmp values ('Acinetobacter baumannii AYE');
insert into tmp values ('Acinetobacter baumannii SDF');
insert into tmp values ('Acinetobacter sp ADP1');
insert into tmp values ('Actinobacillus pleuropneumoniae L20');
insert into tmp values ('Actinobacillus pleuropneumoniae serovar 3 JL03');
insert into tmp values ('Actinobacillus succinogenes 130Z');
insert into tmp values ('Aeromonas hydrophila ATCC 7966');
insert into tmp values ('Aeromonas salmonicida A449');
insert into tmp values ('Aeropyrum pernix');
insert into tmp values ('Agrobacterium tumefaciens C58 Cereon');
insert into tmp values ('Alcanivorax borkumensis SK2');
insert into tmp values ('Alkalilimnicola ehrlichei MLHE-1');
insert into tmp values ('Alkaliphilus metalliredigens QYMF');
insert into tmp values ('Alkaliphilus oremlandii OhILAs');
insert into tmp values ('Anabaena variabilis ATCC 29413');
insert into tmp values ('Anaeromyxobacter dehalogenans 2CP-C');
insert into tmp values ('Anaeromyxobacter Fw109-5');
insert into tmp values ('Anaplasma marginale St Maries');
insert into tmp values ('Anaplasma phagocytophilum HZ');
insert into tmp values ('Aquifex aeolicus');
insert into tmp values ('Archaeoglobus fulgidus');
insert into tmp values ('Arcobacter butzleri RM4018');
insert into tmp values ('Arthrobacter aurescens TC1');
insert into tmp values ('Arthrobacter FB24');
insert into tmp values ('Aster yellows witches-broom phytoplasma AYWB');
insert into tmp values ('Azoarcus BH72');
insert into tmp values ('Azoarcus sp EbN1');
insert into tmp values ('Azorhizobium caulinodans ORS 571');
insert into tmp values ('Bacillus amyloliquefaciens FZB42');
insert into tmp values ('Bacillus anthracis Ames');
insert into tmp values ('Bacillus anthracis Ames 0581');
insert into tmp values ('Bacillus anthracis str Sterne');
insert into tmp values ('Bacillus cereus ATCC 10987');
insert into tmp values ('Bacillus cereus ATCC14579');
insert into tmp values ('Bacillus cereus cytotoxis NVH 391-98');
insert into tmp values ('Bacillus cereus ZK');
insert into tmp values ('Bacillus clausii KSM-K16');
insert into tmp values ('Bacillus halodurans');
insert into tmp values ('Bacillus licheniformis ATCC 14580');
insert into tmp values ('Bacillus licheniformis DSM 13');
insert into tmp values ('Bacillus pumilus SAFR-032');
insert into tmp values ('Bacillus subtilis');
insert into tmp values ('Bacillus thuringiensis Al Hakam');
insert into tmp values ('Bacillus thuringiensis konkukian');
insert into tmp values ('Bacillus weihenstephanensis KBAB4');
insert into tmp values ('Bacteroides fragilis NCTC 9434');
insert into tmp values ('Bacteroides fragilis YCH46');
insert into tmp values ('Bacteroides thetaiotaomicron VPI-5482');
insert into tmp values ('Bacteroides vulgatus ATCC 8482');
insert into tmp values ('Bartonella bacilliformis KC583');
insert into tmp values ('Bartonella henselae Houston-1');
insert into tmp values ('Bartonella quintana Toulouse');
insert into tmp values ('Bartonella tribocorum CIP 105476');
insert into tmp values ('Baumannia cicadellinicola Homalodisca coagulata');
insert into tmp values ('Bdellovibrio bacteriovorus');
insert into tmp values ('Beijerinckia indica ATCC 9039');
insert into tmp values ('Bifidobacterium adolescentis ATCC 15703');
insert into tmp values ('Bifidobacterium longum');
insert into tmp values ('Bordetella avium 197N');
insert into tmp values ('Bordetella bronchiseptica');
insert into tmp values ('Bordetella parapertussis');
insert into tmp values ('Bordetella pertussis');
insert into tmp values ('Bordetella petrii');
insert into tmp values ('Borrelia afzelii PKo');
insert into tmp values ('Borrelia burgdorferi');
insert into tmp values ('Borrelia garinii PBi');
insert into tmp values ('Bradyrhizobium BTAi1');
insert into tmp values ('Bradyrhizobium japonicum');
insert into tmp values ('Bradyrhizobium ORS278');
insert into tmp values ('Brucella abortus 9-941');
insert into tmp values ('Brucella abortus S19');
insert into tmp values ('Brucella canis ATCC 23365');
insert into tmp values ('Brucella melitensis');
insert into tmp values ('Brucella melitensis biovar Abortus');
insert into tmp values ('Brucella ovis');
insert into tmp values ('Brucella suis 1330');
insert into tmp values ('Brucella suis ATCC 23445');
insert into tmp values ('Buchnera aphidicola');
insert into tmp values ('Buchnera aphidicola Cc Cinara cedri');
insert into tmp values ('Buchnera aphidicola Sg');
insert into tmp values ('Buchnera sp');
insert into tmp values ('Burkholderia 383');
insert into tmp values ('Burkholderia ambifaria MC40 6');
insert into tmp values ('Burkholderia cenocepacia AU 1054');
insert into tmp values ('Burkholderia cenocepacia HI2424');
insert into tmp values ('Burkholderia cenocepacia MC0 3');
insert into tmp values ('Burkholderia cepacia AMMD');
insert into tmp values ('Burkholderia mallei ATCC 23344');
insert into tmp values ('Burkholderia mallei NCTC 10229');
insert into tmp values ('Burkholderia mallei NCTC 10247');
insert into tmp values ('Burkholderia mallei SAVP1');
insert into tmp values ('Burkholderia multivorans ATCC 17616');
insert into tmp values ('Burkholderia phymatum STM815');
insert into tmp values ('Burkholderia pseudomallei 1106a');
insert into tmp values ('Burkholderia pseudomallei 1710b');
insert into tmp values ('Burkholderia pseudomallei 668');
insert into tmp values ('Burkholderia pseudomallei K96243');
insert into tmp values ('Burkholderia thailandensis E264');
insert into tmp values ('Burkholderia vietnamiensis G4');
insert into tmp values ('Burkholderia xenovorans LB400');
insert into tmp values ('Caldicellulosiruptor saccharolyticus DSM 8903');
insert into tmp values ('Caldivirga maquilingensis IC-167');
insert into tmp values ('Campylobacter concisus 13826');
insert into tmp values ('Campylobacter curvus 525 92');
insert into tmp values ('Campylobacter fetus 82-40');
insert into tmp values ('Campylobacter hominis ATCC BAA-381');
insert into tmp values ('Campylobacter jejuni');
insert into tmp values ('Campylobacter jejuni 81116');
insert into tmp values ('Campylobacter jejuni 81-176');
insert into tmp values ('Campylobacter jejuni doylei 269 97');
insert into tmp values ('Campylobacter jejuni RM1221');
insert into tmp values ('Candidatus Blochmannia floridanus');
insert into tmp values ('Candidatus Blochmannia pennsylvanicus BPEN');
insert into tmp values ('Candidatus Carsonella ruddii PV');
insert into tmp values ('Candidatus Desulfococcus oleovorans Hxd3');
insert into tmp values ('Candidatus Desulforudis audaxviator MP104C');
insert into tmp values ('Candidatus Korarchaeum cryptofilum OPF8');
insert into tmp values ('Candidatus Methanoregula boonei 6A8');
insert into tmp values ('Candidatus Pelagibacter ubique HTCC1062');
insert into tmp values ('Candidatus Ruthia magnifica Cm Calyptogena magnifica ');
insert into tmp values ('Candidatus Sulcia muelleri GWSS');
insert into tmp values ('Candidatus Vesicomyosocius okutanii HA');
insert into tmp values ('Carboxydothermus hydrogenoformans Z-2901');
insert into tmp values ('Caulobacter crescentus');
insert into tmp values ('Caulobacter K31');
insert into tmp values ('Chlamydia muridarum');
insert into tmp values ('Chlamydia trachomatis');
insert into tmp values ('Chlamydia trachomatis 434 Bu');
insert into tmp values ('Chlamydia trachomatis A HAR-13');
insert into tmp values ('Chlamydia trachomatis L2b UCH 1 proctitis');
insert into tmp values ('Chlamydophila abortus S26 3');
insert into tmp values ('Chlamydophila caviae');
insert into tmp values ('Chlamydophila felis Fe C-56');
insert into tmp values ('Chlamydophila pneumoniae AR39');
insert into tmp values ('Chlamydophila pneumoniae CWL029');
insert into tmp values ('Chlamydophila pneumoniae J138');
insert into tmp values ('Chlamydophila pneumoniae TW 183');
insert into tmp values ('Chlorobium chlorochromatii CaD3');
insert into tmp values ('Chlorobium phaeobacteroides DSM 266');
insert into tmp values ('Chlorobium tepidum TLS');
insert into tmp values ('Chloroflexus aurantiacus J 10 fl');
insert into tmp values ('Chromobacterium violaceum');
insert into tmp values ('Chromohalobacter salexigens DSM 3043');
insert into tmp values ('Citrobacter koseri ATCC BAA-895');
insert into tmp values ('Clavibacter michiganensis NCPPB 382');
insert into tmp values ('Clavibacter michiganensis sepedonicus');
insert into tmp values ('Clostridium acetobutylicum');
insert into tmp values ('Clostridium beijerinckii NCIMB 8052');
insert into tmp values ('Clostridium botulinum A');
insert into tmp values ('Clostridium botulinum A3 Loch Maree');
insert into tmp values ('Clostridium botulinum A ATCC 19397');
insert into tmp values ('Clostridium botulinum A Hall');
insert into tmp values ('Clostridium botulinum B1 Okra');
insert into tmp values ('Clostridium botulinum B Eklund 17B');
insert into tmp values ('Clostridium botulinum F Langeland');
insert into tmp values ('Clostridium difficile 630');
insert into tmp values ('Clostridium kluyveri DSM 555');
insert into tmp values ('Clostridium novyi NT');
insert into tmp values ('Clostridium perfringens');
insert into tmp values ('Clostridium perfringens ATCC 13124');
insert into tmp values ('Clostridium perfringens SM101');
insert into tmp values ('Clostridium phytofermentans ISDg');
insert into tmp values ('Clostridium tetani E88');
insert into tmp values ('Clostridium thermocellum ATCC 27405');
insert into tmp values ('Colwellia psychrerythraea 34H');
insert into tmp values ('Corynebacterium diphtheriae');
insert into tmp values ('Corynebacterium efficiens YS-314');
insert into tmp values ('Corynebacterium glutamicum ATCC 13032 Bielefeld');
insert into tmp values ('Corynebacterium glutamicum ATCC 13032 Kitasato');
insert into tmp values ('Corynebacterium glutamicum R');
insert into tmp values ('Corynebacterium jeikeium K411');
insert into tmp values ('Corynebacterium urealyticum DSM 7109');
insert into tmp values ('Coxiella burnetii');
insert into tmp values ('Coxiella burnetii Dugway 7E9-12');
insert into tmp values ('Coxiella burnetii RSA 331');
insert into tmp values ('Cupriavidus taiwanensis');
insert into tmp values ('Cyanobacteria bacterium Yellowstone A-Prime');
insert into tmp values ('Cyanobacteria bacterium Yellowstone B-Prime');
insert into tmp values ('Cyanothece ATCC 51142');
insert into tmp values ('Cytophaga hutchinsonii ATCC 33406');
insert into tmp values ('Dechloromonas aromatica RCB');
insert into tmp values ('Dehalococcoides BAV1');
insert into tmp values ('Dehalococcoides CBDB1');
insert into tmp values ('Dehalococcoides ethenogenes 195');
insert into tmp values ('Deinococcus geothermalis DSM 11300');
insert into tmp values ('Deinococcus radiodurans');
insert into tmp values ('Delftia acidovorans SPH-1');
insert into tmp values ('Desulfitobacterium hafniense Y51');
insert into tmp values ('Desulfotalea psychrophila LSv54');
insert into tmp values ('Desulfotomaculum reducens MI-1');
insert into tmp values ('Desulfovibrio desulfuricans G20');
insert into tmp values ('Desulfovibrio vulgaris DP4');
insert into tmp values ('Desulfovibrio vulgaris Hildenborough');
insert into tmp values ('Dichelobacter nodosus VCS1703A');
insert into tmp values ('Dinoroseobacter shibae DFL 12');
insert into tmp values ('Ehrlichia canis Jake');
insert into tmp values ('Ehrlichia chaffeensis Arkansas');
insert into tmp values ('Ehrlichia ruminantium Gardel');
insert into tmp values ('Ehrlichia ruminantium str. Welgevonden');
insert into tmp values ('Ehrlichia ruminantium Welgevonden');
insert into tmp values ('Enterobacter 638');
insert into tmp values ('Enterobacter sakazakii ATCC BAA-894');
insert into tmp values ('Enterococcus faecalis V583');
insert into tmp values ('Erwinia carotovora atroseptica SCRI1043');
insert into tmp values ('Erythrobacter litoralis HTCC2594');
insert into tmp values ('Escherichia coli 536');
insert into tmp values ('Escherichia coli APEC O1');
insert into tmp values ('Escherichia coli C ATCC 8739');
insert into tmp values ('Escherichia coli CFT073');
insert into tmp values ('Escherichia coli E24377A');
insert into tmp values ('Escherichia coli HS');
insert into tmp values ('Escherichia coli K 12 substr  DH10B');
insert into tmp values ('Escherichia coli K12 substr  MG1655');
insert into tmp values ('Escherichia coli O157H7');
insert into tmp values ('Escherichia coli O157H7 EDL933');
insert into tmp values ('Escherichia coli SECEC SMS 3 5');
insert into tmp values ('Escherichia coli UTI89');
insert into tmp values ('Escherichia coli W3110');
insert into tmp values ('Exiguobacterium sibiricum 255 15');
insert into tmp values ('Fervidobacterium nodosum Rt17-B1');
insert into tmp values ('Finegoldia magna ATCC 29328');
insert into tmp values ('Flavobacterium johnsoniae UW101');
insert into tmp values ('Flavobacterium psychrophilum JIP02 86');
insert into tmp values ('Francisella philomiragia ATCC 25017');
insert into tmp values ('Francisella tularensis FSC 198');
insert into tmp values ('Francisella tularensis holarctica');
insert into tmp values ('Francisella tularensis holarctica FTA');
insert into tmp values ('Francisella tularensis holarctica OSU18');
insert into tmp values ('Francisella tularensis mediasiatica FSC147');
insert into tmp values ('Francisella tularensis novicida U112');
insert into tmp values ('Francisella tularensis tularensis');
insert into tmp values ('Francisella tularensis WY96-3418');
insert into tmp values ('Frankia alni ACN14a');
insert into tmp values ('Frankia CcI3');
insert into tmp values ('Frankia EAN1pec');
insert into tmp values ('Fusobacterium nucleatum');
insert into tmp values ('Geobacillus kaustophilus HTA426');
insert into tmp values ('Geobacillus thermodenitrificans NG80-2');
insert into tmp values ('Geobacter metallireducens GS-15');
insert into tmp values ('Geobacter sulfurreducens');
insert into tmp values ('Geobacter uraniumreducens Rf4');
insert into tmp values ('Gloeobacter violaceus');
insert into tmp values ('Gluconacetobacter diazotrophicus PAl 5');
insert into tmp values ('Gluconobacter oxydans 621H');
insert into tmp values ('Gramella forsetii KT0803');
insert into tmp values ('Granulobacter bethesdensis CGDNIH1');
insert into tmp values ('Haemophilus ducreyi 35000HP');
insert into tmp values ('Haemophilus influenzae');
insert into tmp values ('Haemophilus influenzae 86 028NP');
insert into tmp values ('Haemophilus influenzae PittEE');
insert into tmp values ('Haemophilus influenzae PittGG');
insert into tmp values ('Haemophilus somnus 129PT');
insert into tmp values ('Haemophilus somnus 2336');
insert into tmp values ('Hahella chejuensis KCTC 2396');
insert into tmp values ('Haloarcula marismortui ATCC 43049');
insert into tmp values ('Halobacterium salinarum R1');
insert into tmp values ('Halobacterium sp');
insert into tmp values ('Haloquadratum walsbyi');
insert into tmp values ('Halorhodospira halophila SL1');
insert into tmp values ('Helicobacter acinonychis Sheeba');
insert into tmp values ('Helicobacter hepaticus');
insert into tmp values ('Helicobacter pylori 26695');
insert into tmp values ('Helicobacter pylori HPAG1');
insert into tmp values ('Helicobacter pylori J99');
insert into tmp values ('Heliobacterium modesticaldum Ice1');
insert into tmp values ('Herminiimonas arsenicoxydans');
insert into tmp values ('Herpetosiphon aurantiacus ATCC 23779');
insert into tmp values ('Hyperthermus butylicus');
insert into tmp values ('Hyphomonas neptunium ATCC 15444');
insert into tmp values ('Idiomarina loihiensis L2TR');
insert into tmp values ('Ignicoccus hospitalis KIN4 I');
insert into tmp values ('Jannaschia CCS1');
insert into tmp values ('Janthinobacterium Marseille');
insert into tmp values ('Kineococcus radiotolerans SRS30216');
insert into tmp values ('Klebsiella pneumoniae MGH 78578');
insert into tmp values ('Lactobacillus acidophilus NCFM');
insert into tmp values ('Lactobacillus brevis ATCC 367');
insert into tmp values ('Lactobacillus casei ATCC 334');
insert into tmp values ('Lactobacillus delbrueckii bulgaricus');
insert into tmp values ('Lactobacillus delbrueckii bulgaricus ATCC BAA-365');
insert into tmp values ('Lactobacillus fermentum IFO 3956');
insert into tmp values ('Lactobacillus gasseri ATCC 33323');
insert into tmp values ('Lactobacillus helveticus DPC 4571');
insert into tmp values ('Lactobacillus johnsonii NCC 533');
insert into tmp values ('Lactobacillus plantarum');
insert into tmp values ('Lactobacillus reuteri F275');
insert into tmp values ('Lactobacillus sakei 23K');
insert into tmp values ('Lactobacillus salivarius UCC118');
insert into tmp values ('Lactococcus lactis');
insert into tmp values ('Lactococcus lactis cremoris MG1363');
insert into tmp values ('Lactococcus lactis cremoris SK11');
insert into tmp values ('Lawsonia intracellularis PHE MN1-00');
insert into tmp values ('Legionella pneumophila Corby');
insert into tmp values ('Legionella pneumophila Lens');
insert into tmp values ('Legionella pneumophila Paris');
insert into tmp values ('Legionella pneumophila Philadelphia 1');
insert into tmp values ('Leifsonia xyli xyli CTCB0');
insert into tmp values ('Leptospira biflexa serovar Patoc  Patoc 1  Paris ');
insert into tmp values ('Leptospira borgpetersenii serovar Hardjo-bovis JB197');
insert into tmp values ('Leptospira borgpetersenii serovar Hardjo-bovis L550');
insert into tmp values ('Leptospira interrogans serovar Copenhageni');
insert into tmp values ('Leptospira interrogans serovar Lai');
insert into tmp values ('Leptothrix cholodnii SP 6');
insert into tmp values ('Leuconostoc citreum KM20');
insert into tmp values ('Leuconostoc mesenteroides ATCC 8293');
insert into tmp values ('Listeria innocua');
insert into tmp values ('Listeria monocytogenes');
insert into tmp values ('Listeria monocytogenes 4b F2365');
insert into tmp values ('Listeria welshimeri serovar 6b SLCC5334');
insert into tmp values ('Lysinibacillus sphaericus C3 41');
insert into tmp values ('Magnetococcus MC-1');
insert into tmp values ('Magnetospirillum magneticum AMB-1');
insert into tmp values ('Mannheimia succiniciproducens MBEL55E');
insert into tmp values ('Maricaulis maris MCS10');
insert into tmp values ('Marinobacter aquaeolei VT8');
insert into tmp values ('Marinomonas MWYL1');
insert into tmp values ('Mesoplasma florum L1');
insert into tmp values ('Mesorhizobium BNC1');
insert into tmp values ('Mesorhizobium loti');
insert into tmp values ('Metallosphaera sedula DSM 5348');
insert into tmp values ('Methanobacterium thermoautotrophicum');
insert into tmp values ('Methanobrevibacter smithii ATCC 35061');
insert into tmp values ('Methanococcoides burtonii DSM 6242');
insert into tmp values ('Methanococcus aeolicus Nankai-3');
insert into tmp values ('Methanococcus jannaschii');
insert into tmp values ('Methanococcus maripaludis C5');
insert into tmp values ('Methanococcus maripaludis C6');
insert into tmp values ('Methanococcus maripaludis C7');
insert into tmp values ('Methanococcus maripaludis S2');
insert into tmp values ('Methanococcus vannielii SB');
insert into tmp values ('Methanocorpusculum labreanum Z');
insert into tmp values ('Methanoculleus marisnigri JR1');
insert into tmp values ('Methanopyrus kandleri');
insert into tmp values ('Methanosaeta thermophila PT');
insert into tmp values ('Methanosarcina acetivorans');
insert into tmp values ('Methanosarcina barkeri fusaro');
insert into tmp values ('Methanosarcina mazei');
insert into tmp values ('Methanosphaera stadtmanae');
insert into tmp values ('Methanospirillum hungatei JF-1');
insert into tmp values ('Methylibium petroleiphilum PM1');
insert into tmp values ('Methylobacillus flagellatus KT');
insert into tmp values ('Methylobacterium 4 46');
insert into tmp values ('Methylobacterium extorquens PA1');
insert into tmp values ('Methylobacterium radiotolerans JCM 2831');
insert into tmp values ('Methylococcus capsulatus Bath');
insert into tmp values ('Microcystis aeruginosa NIES 843');
insert into tmp values ('Moorella thermoacetica ATCC 39073');
insert into tmp values ('Mycobacterium abscessus ATCC 19977T');
insert into tmp values ('Mycobacterium avium 104');
insert into tmp values ('Mycobacterium avium paratuberculosis');
insert into tmp values ('Mycobacterium bovis');
insert into tmp values ('Mycobacterium bovis BCG Pasteur 1173P2');
insert into tmp values ('Mycobacterium gilvum PYR-GCK');
insert into tmp values ('Mycobacterium JLS');
insert into tmp values ('Mycobacterium KMS');
insert into tmp values ('Mycobacterium leprae');
insert into tmp values ('Mycobacterium marinum M');
insert into tmp values ('Mycobacterium MCS');
insert into tmp values ('Mycobacterium smegmatis MC2 155');
insert into tmp values ('Mycobacterium tuberculosis CDC1551');
insert into tmp values ('Mycobacterium tuberculosis F11');
insert into tmp values ('Mycobacterium tuberculosis H37Ra');
insert into tmp values ('Mycobacterium tuberculosis H37Rv');
insert into tmp values ('Mycobacterium ulcerans Agy99');
insert into tmp values ('Mycobacterium vanbaalenii PYR-1');
insert into tmp values ('Mycoplasma agalactiae PG2');
insert into tmp values ('Mycoplasma capricolum ATCC 27343');
insert into tmp values ('Mycoplasma gallisepticum');
insert into tmp values ('Mycoplasma genitalium');
insert into tmp values ('Mycoplasma hyopneumoniae 232');
insert into tmp values ('Mycoplasma hyopneumoniae 7448');
insert into tmp values ('Mycoplasma hyopneumoniae J');
insert into tmp values ('Mycoplasma mobile 163K');
insert into tmp values ('Mycoplasma mycoides');
insert into tmp values ('Mycoplasma penetrans');
insert into tmp values ('Mycoplasma pneumoniae');
insert into tmp values ('Mycoplasma pulmonis');
insert into tmp values ('Mycoplasma synoviae 53');
insert into tmp values ('Myxococcus xanthus DK 1622');
insert into tmp values ('Nanoarchaeum equitans');
insert into tmp values ('Natronomonas pharaonis');
insert into tmp values ('Neisseria gonorrhoeae FA 1090');
insert into tmp values ('Neisseria meningitidis 053442');
insert into tmp values ('Neisseria meningitidis FAM18');
insert into tmp values ('Neisseria meningitidis MC58');
insert into tmp values ('Neisseria meningitidis Z2491');
insert into tmp values ('Neorickettsia sennetsu Miyayama');
insert into tmp values ('Nitratiruptor SB155-2');
insert into tmp values ('Nitrobacter hamburgensis X14');
insert into tmp values ('Nitrobacter winogradskyi Nb-255');
insert into tmp values ('Nitrosococcus oceani ATCC 19707');
insert into tmp values ('Nitrosomonas europaea');
insert into tmp values ('Nitrosomonas eutropha C71');
insert into tmp values ('Nitrosopumilus maritimus SCM1');
insert into tmp values ('Nitrosospira multiformis ATCC 25196');
insert into tmp values ('Nocardia farcinica IFM10152');
insert into tmp values ('Nocardioides JS614');
insert into tmp values ('Nostoc sp');
insert into tmp values ('Novosphingobium aromaticivorans DSM 12444');
insert into tmp values ('Oceanobacillus iheyensis');
insert into tmp values ('Ochrobactrum anthropi ATCC 49188');
insert into tmp values ('Oenococcus oeni PSU-1');
insert into tmp values ('Onion yellows phytoplasma');
insert into tmp values ('Opitutus terrae PB90 1');
insert into tmp values ('Orientia tsutsugamushi Boryong');
insert into tmp values ('Orientia tsutsugamushi Ikeda');
insert into tmp values ('Parabacteroides distasonis ATCC 8503');
insert into tmp values ('Parachlamydia sp UWE25');
insert into tmp values ('Paracoccus denitrificans PD1222');
insert into tmp values ('Parvibaculum lavamentivorans DS-1');
insert into tmp values ('Pasteurella multocida');
insert into tmp values ('Pediococcus pentosaceus ATCC 25745');
insert into tmp values ('Pelobacter carbinolicus');
insert into tmp values ('Pelobacter propionicus DSM 2379');
insert into tmp values ('Pelodictyon luteolum DSM 273');
insert into tmp values ('Pelotomaculum thermopropionicum SI');
insert into tmp values ('Petrotoga mobilis SJ95');
insert into tmp values ('Photobacterium profundum SS9');
insert into tmp values ('Photorhabdus luminescens');
insert into tmp values ('Picrophilus torridus DSM 9790');
insert into tmp values ('Pirellula sp');
insert into tmp values ('Polaromonas JS666');
insert into tmp values ('Polaromonas naphthalenivorans CJ2');
insert into tmp values ('Polynucleobacter necessarius STIR1');
insert into tmp values ('Polynucleobacter QLW-P1DMWA-1');
insert into tmp values ('Porphyromonas gingivalis W83');
insert into tmp values ('Prochlorococcus marinus AS9601');
insert into tmp values ('Prochlorococcus marinus CCMP1375');
insert into tmp values ('Prochlorococcus marinus MED4');
insert into tmp values ('Prochlorococcus marinus MIT 9211');
insert into tmp values ('Prochlorococcus marinus MIT 9215');
insert into tmp values ('Prochlorococcus marinus MIT 9301');
insert into tmp values ('Prochlorococcus marinus MIT 9303');
insert into tmp values ('Prochlorococcus marinus MIT 9312');
insert into tmp values ('Prochlorococcus marinus MIT9313');
insert into tmp values ('Prochlorococcus marinus MIT 9515');
insert into tmp values ('Prochlorococcus marinus NATL1A');
insert into tmp values ('Prochlorococcus marinus NATL2A');
insert into tmp values ('Propionibacterium acnes KPA171202');
insert into tmp values ('Prosthecochloris vibrioformis DSM 265');
insert into tmp values ('Pseudoalteromonas atlantica T6c');
insert into tmp values ('Pseudoalteromonas haloplanktis TAC125');
insert into tmp values ('Pseudomonas aeruginosa');
insert into tmp values ('Pseudomonas aeruginosa PA7');
insert into tmp values ('Pseudomonas aeruginosa UCBPP-PA14');
insert into tmp values ('Pseudomonas entomophila L48');
insert into tmp values ('Pseudomonas fluorescens Pf-5');
insert into tmp values ('Pseudomonas fluorescens PfO-1');
insert into tmp values ('Pseudomonas mendocina ymp');
insert into tmp values ('Pseudomonas putida F1');
insert into tmp values ('Pseudomonas putida GB 1');
insert into tmp values ('Pseudomonas putida KT2440');
insert into tmp values ('Pseudomonas putida W619');
insert into tmp values ('Pseudomonas stutzeri A1501');
insert into tmp values ('Pseudomonas syringae phaseolicola 1448A');
insert into tmp values ('Pseudomonas syringae pv B728a');
insert into tmp values ('Pseudomonas syringae tomato DC3000');
insert into tmp values ('Psychrobacter arcticum 273-4');
insert into tmp values ('Psychrobacter cryohalolentis K5');
insert into tmp values ('Psychrobacter PRwf-1');
insert into tmp values ('Psychromonas ingrahamii 37');
insert into tmp values ('Pyrobaculum aerophilum');
insert into tmp values ('Pyrobaculum arsenaticum DSM 13514');
insert into tmp values ('Pyrobaculum calidifontis JCM 11548');
insert into tmp values ('Pyrobaculum islandicum DSM 4184');
insert into tmp values ('Pyrococcus abyssi');
insert into tmp values ('Pyrococcus furiosus');
insert into tmp values ('Pyrococcus horikoshii');
insert into tmp values ('Ralstonia eutropha H16');
insert into tmp values ('Ralstonia eutropha JMP134');
insert into tmp values ('Ralstonia metallidurans CH34');
insert into tmp values ('Ralstonia solanacearum');
insert into tmp values ('Renibacterium salmoninarum ATCC 33209');
insert into tmp values ('Rhizobium etli CFN 42');
insert into tmp values ('Rhizobium leguminosarum bv viciae 3841');
insert into tmp values ('Rhodobacter sphaeroides 2 4 1');
insert into tmp values ('Rhodobacter sphaeroides ATCC 17025');
insert into tmp values ('Rhodobacter sphaeroides ATCC 17029');
insert into tmp values ('Rhodococcus RHA1');
insert into tmp values ('Rhodoferax ferrireducens T118');
insert into tmp values ('Rhodopseudomonas palustris BisA53');
insert into tmp values ('Rhodopseudomonas palustris BisB18');
insert into tmp values ('Rhodopseudomonas palustris BisB5');
insert into tmp values ('Rhodopseudomonas palustris CGA009');
insert into tmp values ('Rhodopseudomonas palustris HaA2');
insert into tmp values ('Rhodospirillum rubrum ATCC 11170');
insert into tmp values ('Rickettsia akari Hartford');
insert into tmp values ('Rickettsia bellii OSU 85-389');
insert into tmp values ('Rickettsia bellii RML369-C');
insert into tmp values ('Rickettsia canadensis McKiel');
insert into tmp values ('Rickettsia conorii');
insert into tmp values ('Rickettsia felis URRWXCal2');
insert into tmp values ('Rickettsia massiliae MTU5');
insert into tmp values ('Rickettsia prowazekii');
insert into tmp values ('Rickettsia rickettsii Iowa');
insert into tmp values ('Rickettsia rickettsii Sheila Smith');
insert into tmp values ('Rickettsia typhi wilmington');
insert into tmp values ('Roseiflexus castenholzii DSM 13941');
insert into tmp values ('Roseiflexus RS-1');
insert into tmp values ('Roseobacter denitrificans OCh 114');
insert into tmp values ('Rubrobacter xylanophilus DSM 9941');
insert into tmp values ('Saccharophagus degradans 2-40');
insert into tmp values ('Saccharopolyspora erythraea NRRL 2338');
insert into tmp values ('Salinibacter ruber DSM 13855');
insert into tmp values ('Salinispora arenicola CNS-205');
insert into tmp values ('Salinispora tropica CNB-440');
insert into tmp values ('Salmonella enterica arizonae serovar 62 z4 z23  ');
insert into tmp values ('Salmonella enterica Choleraesuis');
insert into tmp values ('Salmonella enterica Paratypi ATCC 9150');
insert into tmp values ('Salmonella enterica serovar Paratyphi B SPB7');
insert into tmp values ('Salmonella typhi');
insert into tmp values ('Salmonella typhimurium LT2');
insert into tmp values ('Salmonella typhi Ty2');
insert into tmp values ('Serratia proteamaculans 568');
insert into tmp values ('Shewanella amazonensis SB2B');
insert into tmp values ('Shewanella ANA-3');
insert into tmp values ('Shewanella baltica OS155');
insert into tmp values ('Shewanella baltica OS185');
insert into tmp values ('Shewanella baltica OS195');
insert into tmp values ('Shewanella denitrificans OS217');
insert into tmp values ('Shewanella frigidimarina NCIMB 400');
insert into tmp values ('Shewanella halifaxensis HAW EB4');
insert into tmp values ('Shewanella loihica PV-4');
insert into tmp values ('Shewanella MR-4');
insert into tmp values ('Shewanella MR-7');
insert into tmp values ('Shewanella oneidensis');
insert into tmp values ('Shewanella pealeana ATCC 700345');
insert into tmp values ('Shewanella putrefaciens CN-32');
insert into tmp values ('Shewanella sediminis HAW-EB3');
insert into tmp values ('Shewanella W3-18-1');
insert into tmp values ('Shewanella woodyi ATCC 51908');
insert into tmp values ('Shigella boydii CDC 3083 94');
insert into tmp values ('Shigella boydii Sb227');
insert into tmp values ('Shigella dysenteriae');
insert into tmp values ('Shigella flexneri 2a');
insert into tmp values ('Shigella flexneri 2a 2457T');
insert into tmp values ('Shigella flexneri 5 8401');
insert into tmp values ('Shigella sonnei Ss046');
insert into tmp values ('Silicibacter pomeroyi DSS-3');
insert into tmp values ('Silicibacter TM1040');
insert into tmp values ('Sinorhizobium medicae WSM419');
insert into tmp values ('Sinorhizobium meliloti');
insert into tmp values ('Sodalis glossinidius morsitans');
insert into tmp values ('Solibacter usitatus Ellin6076');
insert into tmp values ('Sorangium cellulosum  So ce 56 ');
insert into tmp values ('Sphingomonas wittichii RW1');
insert into tmp values ('Sphingopyxis alaskensis RB2256');
insert into tmp values ('Staphylococcus aureus aureus MRSA252');
insert into tmp values ('Staphylococcus aureus aureus MSSA476');
insert into tmp values ('Staphylococcus aureus COL');
insert into tmp values ('Staphylococcus aureus JH1');
insert into tmp values ('Staphylococcus aureus JH9');
insert into tmp values ('Staphylococcus aureus Mu3');
insert into tmp values ('Staphylococcus aureus Mu50');
insert into tmp values ('Staphylococcus aureus MW2');
insert into tmp values ('Staphylococcus aureus N315');
insert into tmp values ('Staphylococcus aureus NCTC 8325');
insert into tmp values ('Staphylococcus aureus Newman');
insert into tmp values ('Staphylococcus aureus RF122');
insert into tmp values ('Staphylococcus aureus USA300');
insert into tmp values ('Staphylococcus aureus USA300 TCH1516');
insert into tmp values ('Staphylococcus epidermidis ATCC 12228');
insert into tmp values ('Staphylococcus epidermidis RP62A');
insert into tmp values ('Staphylococcus haemolyticus');
insert into tmp values ('Staphylococcus saprophyticus');
insert into tmp values ('Staphylothermus marinus F1');
insert into tmp values ('Streptococcus agalactiae 2603');
insert into tmp values ('Streptococcus agalactiae A909');
insert into tmp values ('Streptococcus agalactiae NEM316');
insert into tmp values ('Streptococcus gordonii Challis substr CH1');
insert into tmp values ('Streptococcus mutans');
insert into tmp values ('Streptococcus pneumoniae CGSP14');
insert into tmp values ('Streptococcus pneumoniae D39');
insert into tmp values ('Streptococcus pneumoniae Hungary19A 6');
insert into tmp values ('Streptococcus pneumoniae R6');
insert into tmp values ('Streptococcus pneumoniae TIGR4');
insert into tmp values ('Streptococcus pyogenes M1 GAS');
insert into tmp values ('Streptococcus pyogenes Manfredo');
insert into tmp values ('Streptococcus pyogenes MGAS10270');
insert into tmp values ('Streptococcus pyogenes MGAS10394');
insert into tmp values ('Streptococcus pyogenes MGAS10750');
insert into tmp values ('Streptococcus pyogenes MGAS2096');
insert into tmp values ('Streptococcus pyogenes MGAS315');
insert into tmp values ('Streptococcus pyogenes MGAS5005');
insert into tmp values ('Streptococcus pyogenes MGAS6180');
insert into tmp values ('Streptococcus pyogenes MGAS8232');
insert into tmp values ('Streptococcus pyogenes MGAS9429');
insert into tmp values ('Streptococcus pyogenes SSI-1');
insert into tmp values ('Streptococcus sanguinis SK36');
insert into tmp values ('Streptococcus suis 05ZYH33');
insert into tmp values ('Streptococcus suis 98HAH33');
insert into tmp values ('Streptococcus thermophilus CNRZ1066');
insert into tmp values ('Streptococcus thermophilus LMD-9');
insert into tmp values ('Streptococcus thermophilus LMG 18311');
insert into tmp values ('Streptomyces avermitilis');
insert into tmp values ('Streptomyces coelicolor');
insert into tmp values ('Streptomyces griseus NBRC 13350');
insert into tmp values ('Sulfolobus acidocaldarius DSM 639');
insert into tmp values ('Sulfolobus solfataricus');
insert into tmp values ('Sulfolobus tokodaii');
insert into tmp values ('Sulfurovum NBC37-1');
insert into tmp values ('Symbiobacterium thermophilum IAM14863');
insert into tmp values ('Synechococcus CC9311');
insert into tmp values ('Synechococcus CC9605');
insert into tmp values ('Synechococcus CC9902');
insert into tmp values ('Synechococcus elongatus PCC 6301');
insert into tmp values ('Synechococcus elongatus PCC 7942');
insert into tmp values ('Synechococcus PCC 7002');
insert into tmp values ('Synechococcus RCC307');
insert into tmp values ('Synechococcus sp WH8102');
insert into tmp values ('Synechococcus WH 7803');
insert into tmp values ('Synechocystis PCC6803');
insert into tmp values ('Syntrophobacter fumaroxidans MPOB');
insert into tmp values ('Syntrophomonas wolfei Goettingen');
insert into tmp values ('Syntrophus aciditrophicus SB');
insert into tmp values ('Thermoanaerobacter pseudethanolicus ATCC 33223');
insert into tmp values ('Thermoanaerobacter tengcongensis');
insert into tmp values ('Thermoanaerobacter X514');
insert into tmp values ('Thermobifida fusca YX');
insert into tmp values ('Thermococcus kodakaraensis KOD1');
insert into tmp values ('Thermofilum pendens Hrk 5');
insert into tmp values ('Thermoplasma acidophilum');
insert into tmp values ('Thermoplasma volcanium');
insert into tmp values ('Thermoproteus neutrophilus V24Sta');
insert into tmp values ('Thermosipho melanesiensis BI429');
insert into tmp values ('Thermosynechococcus elongatus');
insert into tmp values ('Thermotoga lettingae TMO');
insert into tmp values ('Thermotoga maritima');
insert into tmp values ('Thermotoga petrophila RKU-1');
insert into tmp values ('Thermotoga RQ2');
insert into tmp values ('Thermus thermophilus HB27');
insert into tmp values ('Thermus thermophilus HB8');
insert into tmp values ('Thiobacillus denitrificans ATCC 25259');
insert into tmp values ('Thiomicrospira crunogena XCL-2');
insert into tmp values ('Thiomicrospira denitrificans ATCC 33889');
insert into tmp values ('Treponema denticola ATCC 35405');
insert into tmp values ('Treponema pallidum');
insert into tmp values ('Trichodesmium erythraeum IMS101');
insert into tmp values ('Tropheryma whipplei TW08 27');
insert into tmp values ('Tropheryma whipplei Twist');
insert into tmp values ('uncultured methanogenic archaeon RC-I');
insert into tmp values ('Ureaplasma parvum serovar 3 ATCC 27815');
insert into tmp values ('Ureaplasma urealyticum');
insert into tmp values ('Verminephrobacter eiseniae EF01-2');
insert into tmp values ('Vibrio cholerae');
insert into tmp values ('Vibrio cholerae O395');
insert into tmp values ('Vibrio fischeri ES114');
insert into tmp values ('Vibrio harveyi ATCC BAA-1116');
insert into tmp values ('Vibrio parahaemolyticus');
insert into tmp values ('Vibrio vulnificus CMCP6');
insert into tmp values ('Vibrio vulnificus YJ016');
insert into tmp values ('Wigglesworthia brevipalpis');
insert into tmp values ('Wolbachia endosymbiont of Brugia malayi TRS');
insert into tmp values ('Wolbachia endosymbiont of Drosophila melanogaster');
insert into tmp values ('Wolinella succinogenes');
insert into tmp values ('Xanthobacter autotrophicus Py2');
insert into tmp values ('Xanthomonas campestris');
insert into tmp values ('Xanthomonas campestris 8004');
insert into tmp values ('Xanthomonas campestris vesicatoria 85-10');
insert into tmp values ('Xanthomonas citri');
insert into tmp values ('Xanthomonas oryzae KACC10331');
insert into tmp values ('Xanthomonas oryzae MAFF 311018');
insert into tmp values ('Xylella fastidiosa');
insert into tmp values ('Xylella fastidiosa M12');
insert into tmp values ('Xylella fastidiosa M23');
insert into tmp values ('Xylella fastidiosa Temecula1');
insert into tmp values ('Yersinia enterocolitica 8081');
insert into tmp values ('Yersinia pestis Angola');
insert into tmp values ('Yersinia pestis Antiqua');
insert into tmp values ('Yersinia pestis biovar Mediaevails');
insert into tmp values ('Yersinia pestis CO92');
insert into tmp values ('Yersinia pestis KIM');
insert into tmp values ('Yersinia pestis Nepal516');
insert into tmp values ('Yersinia pestis Pestoides F');
insert into tmp values ('Yersinia pseudotuberculosis IP 31758');
insert into tmp values ('Yersinia pseudotuberculosis IP32953');
insert into tmp values ('Yersinia pseudotuberculosis YPIII');
insert into tmp values ('Zymomonas mobilis ZM4');

select name_txt, tax_id from tmp LEFT OUTER JOIN names USING (name_txt) where tax_id is null;
